import { useRef, useState } from "react";
import { Building2, Check, CheckCircle2, Dog, FileText, Home, Info, MapPin, ShieldCheck, Upload, X } from "lucide-react";
import { useLocation, useNavigate } from "react-router-dom";
import { BackButton } from "../components/common/BackButton";
import "../styles/situationFlows.css";

type HomeType = "apartment" | "house";
type RateReason = "standard" | "reduced" | "exempt";

export function DogRegistrationPage() {
  const navigate = useNavigate();
  const location = useLocation();
  const fromDogFee = Boolean((location.state as { fromDogFee?: boolean } | null)?.fromDogFee);
  const fileInput = useRef<HTMLInputElement>(null);
  const [name, setName] = useState("");
  const [birthDate, setBirthDate] = useState("");
  const [chip, setChip] = useState("");
  const [breed, setBreed] = useState("");
  const [homeType, setHomeType] = useState<HomeType>("apartment");
  const [rateReason, setRateReason] = useState<RateReason>("standard");
  const [fileName, setFileName] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const standardRate = homeType === "apartment" ? 1500 : 750;
  const amount = rateReason === "exempt" ? 0 : rateReason === "reduced" ? 300 : standardRate;
  const ready = Boolean(name.trim() && birthDate && chip.trim() && breed.trim() && (rateReason === "standard" || fileName));

  if (submitted) return <main className="situation-page"><div className="situation-page__inner situation-success"><span><CheckCircle2 size={40} /></span><p>Elektronické ohlášení bylo odesláno</p><h1>Údaje o psovi {name} byly přijaty</h1><div className="dog-registration-result"><Dog size={30} /><span><strong>{name}</strong><small>{breed} · čip {chip}</small></span><b>{amount.toLocaleString("cs-CZ")} Kč / rok</b></div><ul><li><Check size={17} /> Ohlášení bylo elektronicky odesláno</li><li><Check size={17} /> Sazba byla určena jako pro třetího psa</li><li><Check size={17} /> Platební údaje jsou připravené</li></ul><p>Toto je ukázkový průchod. Po návratu zůstane v evidenci připravený stav se psy Rex a Bella.</p><button type="button" onClick={() => navigate("/poplatek-za-psa")}>Přejít na evidenci a platbu</button><button className="situation-link-button" type="button" onClick={() => navigate("/moje-podani")}>Zobrazit podání</button></div></main>;

  return <main className="situation-page"><div className="situation-page__inner">
    <BackButton className="situation-back" onClick={() => navigate(fromDogFee ? "/poplatek-za-psa" : "/zivotni-situace")} />
    <header className="situation-hero situation-hero--dog"><div><p>Kompletně online</p><h1>Pořídil jsem si psa</h1><span>Psa přihlásíte městu, zjistíte správnou sazbu a rovnou získáte údaje k platbě.</span></div><aside><small>Termín ohlášení</small><strong>do 15 dnů</strong><span>od pořízení psa staršího 3 měsíců</span></aside></header>
    <div className="situation-facts"><span><ShieldCheck size={19} /><b>Bez návštěvy úřadu</b></span><span><MapPin size={19} /><b>Oblast určíme z adresy</b></span><span><Dog size={19} /><b>Sazbu vysvětlíme před odesláním</b></span></div>
    <div className="situation-layout"><form className="situation-form" onSubmit={(event) => { event.preventDefault(); if (ready) setSubmitted(true); }}><p className="form-required-note"><span>*</span> Všechna pole s údaji o psovi jsou povinná. Doklad přiložíte jen při nižší sazbě nebo osvobození.</p>
      <section className="situation-step"><header><b>1</b><div><p>Údaje o psovi</p><h2>Koho přihlašujete?</h2></div></header><div className="situation-fields"><label className="situation-field"><span>Jméno psa</span><div><Dog size={18} /><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Například Bella" /></div></label><label className="situation-field"><span>Datum narození</span><div><input type="date" value={birthDate} onChange={(event) => setBirthDate(event.target.value)} /></div></label><label className="situation-field"><span>Plemeno</span><div><input value={breed} onChange={(event) => setBreed(event.target.value)} placeholder="Například labradorský retrívr" /></div></label><label className="situation-field"><span>Číslo mikročipu</span><div><input inputMode="numeric" value={chip} onChange={(event) => setChip(event.target.value)} placeholder="15místné číslo čipu" /></div></label></div></section>
      <section className="situation-step"><header><b>2</b><div><p>Výpočet sazby</p><h2>V jakém domě bydlíte?</h2></div></header><div className="dog-registration-address"><ShieldCheck size={20} /><span><strong>Oblast jsme určili automaticky</strong><small>Dlouhá 123, Zlín · oblast uvedená v příloze č. 1 vyhlášky</small></span></div><div className="dog-registration-home">{([["apartment","Bytový dům",Building2],["house","Rodinný dům",Home]] as const).map(([value,label,Icon]) => <button className={homeType === value ? "is-active" : ""} type="button" onClick={() => setHomeType(value)} key={value}><Icon size={23} /><span><strong>{label}</strong><small>{value === "apartment" ? "Bytový nebo panelový dům" : "Rodinný dům nebo jiný objekt"}</small></span>{homeType === value && <Check size={17} />}</button>)}</div><div className="dog-registration-order"><Info size={18} /><span>V evidenci už máte psy Rex a Bella. Nového psa proto počítáme jako <strong>třetího psa</strong>.</span></div></section>
      <section className="situation-step"><header><b>3</b><div><p>Nižší sazba</p><h2>Týká se vás některá z možností?</h2></div></header><div className="dog-registration-rates"><button className={rateReason === "standard" ? "is-active" : ""} type="button" onClick={() => { setRateReason("standard"); setFileName(""); }}><strong>Ne, běžná sazba</strong><small>Není potřeba nic dokládat</small></button><button className={rateReason === "reduced" ? "is-active" : ""} type="button" onClick={() => setRateReason("reduced")}><strong>Je mi 65+ nebo splňuji podmínku důchodu</strong><small>Snížená sazba 200 / 300 Kč</small></button><button className={rateReason === "exempt" ? "is-active" : ""} type="button" onClick={() => setRateReason("exempt")}><strong>Mám nárok na osvobození</strong><small>Například ZTP/P, asistenční pes, pes z útulku nebo po kastraci</small></button></div>{rateReason !== "standard" && <><input ref={fileInput} hidden type="file" accept="application/pdf,image/*" onChange={(event) => setFileName(event.target.files?.[0]?.name ?? "")} />{fileName ? <div className="situation-file"><FileText size={20} /><span><strong>{fileName}</strong><small>Doklad je připravený</small></span><button type="button" onClick={() => setFileName("")}><X size={17} /></button></div> : <button className="situation-upload" type="button" onClick={() => fileInput.current?.click()}><Upload size={21} /><span><strong>Přiložit doklad</strong><small>PDF, JPG nebo PNG</small></span></button>}</>}</section>
      <section className="dog-rate-summary"><div><small>Vypočtený roční poplatek</small><strong>{amount.toLocaleString("cs-CZ")} Kč</strong></div><ul><li><Check size={16} /> Třetí pes</li><li><Check size={16} /> {homeType === "apartment" ? "Bytový dům" : "Rodinný dům"}</li><li><Check size={16} /> {rateReason === "standard" ? "Běžná sazba" : rateReason === "reduced" ? "Snížená sazba" : "Osvobození"}</li></ul><p>Částku jsme určili z adresy, typu bydlení, pořadí psa a zvolené sazby. Pokud se údaje při kontrole změní, město vás upozorní před splatností.</p></section>
      <label className="situation-confirm"><input type="checkbox" required /><span>Potvrzuji, že uvedené údaje jsou správné a že jsem držitelem psa.</span></label><button className="situation-submit" type="submit" disabled={!ready}>Přihlásit psa online <CheckCircle2 size={18} /></button>
    </form>
    <aside className="situation-payment situation-payment--summary"><header><span><Dog size={23} /></span><div><p>Průběžné shrnutí</p><h2>{name || "Nový pes"}</h2></div></header><dl><div><dt>Držitel</dt><dd>Jan Novák</dd></div><div><dt>Adresa</dt><dd>Dlouhá 123, Zlín</dd></div><div><dt>Pořadí</dt><dd>Třetí pes</dd></div><div><dt>Roční sazba</dt><dd>{amount.toLocaleString("cs-CZ")} Kč</dd></div></dl><p>Po odeslání zobrazíme potvrzení a platební údaje. Tento prezentační formulář obsah evidence trvale nezmění.</p></aside>
    </div>
    <section className="dog-detailed-info"><h2>Podrobné informace o poplatku</h2><p>Základní formulář obsahuje jen údaje potřebné k ohlášení. Zde najdete sazby, lhůty a úplnější podmínky.</p>
      <details><summary>Komu vzniká povinnost a dokdy psa ohlásit? <span>+</span></summary><div><p>Poplatek platí držitel psa staršího 3 měsíců, který je přihlášený nebo má sídlo na území města Zlína. Vznik povinnosti, změnu údajů nebo její zánik je potřeba oznámit do 15 dnů.</p><p>Poplatek je splatný do 30. 4. 2026. Vznikne-li povinnost později, je poplatek nebo jeho poměrná část splatná do jednoho měsíce.</p></div></details>
      <details><summary>Sazby pro rok 2026 <span>+</span></summary><div><h3>Oblast uvedená v příloze č. 1 vyhlášky</h3><div className="dog-rate-table"><span>Typ bydlení</span><b>První pes</b><b>Další pes</b><span>Bytový dům</span><strong>1 000 Kč</strong><strong>1 500 Kč</strong><span>Rodinný dům nebo jiný objekt</span><strong>500 Kč</strong><strong>750 Kč</strong></div><h3>Ostatní části města</h3><div className="dog-rate-table"><span>Typ bydlení</span><b>První pes</b><b>Další pes</b><span>Bytový dům</span><strong>500 Kč</strong><strong>1 000 Kč</strong><span>Rodinný dům nebo jiný objekt</span><strong>200 Kč</strong><strong>500 Kč</strong></div><p>U osob starších 65 let a vybraných příjemců důchodu činí sazba 200 Kč za prvního a 300 Kč za každého dalšího psa bez ohledu na oblast a typ domu.</p></div></details>
      <details><summary>Kdo může být od poplatku osvobozen? <span>+</span></summary><div><p>Osvobození se může týkat zejména nevidomých osob, osob závislých na pomoci jiné osoby, držitelů průkazu ZTP nebo ZTP/P, držitelů asistenčních, záchranářských, služebních či canisterapeutických psů a provozovatelů útulků.</p><p>Dále může jít o psa převzatého ze zlínského útulku po dobu 24 měsíců nebo psa po kastraci po dobu 12 měsíců. Nárok je nutné doložit ve stanovené lhůtě.</p></div></details>
      <details><summary>Kontakty, formuláře a právní podklady <span>+</span></summary><div><p>Agendu spravuje Odbor právní, oddělení správy poplatků a vymáhání pohledávek, Zarámí 4421, 2. patro, dveře 232.</p><p>Dotazy: <a href="mailto:komunal@zlin.eu">komunal@zlin.eu</a> · datová schránka města: 5ttb7bs.</p><p><a href="https://www.zlin.eu/pes" target="_blank" rel="noreferrer">Formuláře k poplatku ze psů</a> · <a href="https://zlin.eu/obecne-zavazne-vyhlasky-a-narizeni" target="_blank" rel="noreferrer">Vyhláška č. 9/2023</a></p></div></details>
    </section>
  </div></main>;
}
