import { useRef, useState } from "react";
import { Building2, CalendarDays, Check, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, CreditCard, FileText, Info, MapPin, QrCode, ShieldCheck, Upload, X } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { BackButton } from "../components/common/BackButton";
import "../styles/situationFlows.css";

const addressSuggestions = ["Dlouhá 123, Zlín", "Dlouhá 4217, Zlín", "třída Tomáše Bati 508, Zlín", "Štefánikova 167, Zlín", "Podlesí IV 5302, Zlín"];
const calendarDays = Array.from({ length: 31 }, (_, index) => index + 1);
const availableDays = [27, 28, 29, 31];
const timeSlots = ["08:20", "09:00", "10:20", "13:40", "15:20"];

function isUnder15(birthNumber: string) {
  const digits = birthNumber.replace(/\D/g, "");
  if (digits.length < 6) return false;
  const shortYear = Number(digits.slice(0, 2));
  const year = shortYear <= 26 ? 2000 + shortYear : 1900 + shortYear;
  return 2026 - year < 15;
}

export function MovingSituationPage() {
  const navigate = useNavigate();
  const fileInput = useRef<HTMLInputElement>(null);
  const [address, setAddress] = useState("");
  const [includeSelf, setIncludeSelf] = useState(true);
  const [entrustedPeople, setEntrustedPeople] = useState<string[]>([]);
  const [savedPeople, setSavedPeople] = useState<boolean[]>([]);
  const [exemptPeople, setExemptPeople] = useState<boolean[]>([]);
  const [showSuggestions, setShowSuggestions] = useState(false);
  const [proofType, setProofType] = useState("tenant");
  const [fileName, setFileName] = useState("");
  const [paymentChoice, setPaymentChoice] = useState<"" | "qr" | "office" | "exempt">("");
  const [selectedDay, setSelectedDay] = useState<number | null>(28);
  const [selectedTime, setSelectedTime] = useState("10:20");
  const [submitted, setSubmitted] = useState(false);
  const proofReady = proofType === "owner" || Boolean(fileName);
  const personReady = includeSelf || savedPeople.some(Boolean);
  const totalFee = (includeSelf ? 50 : 0) + savedPeople.reduce((sum, saved, index) => sum + (saved && !exemptPeople[index] ? 50 : 0), 0);
  const paymentReady = totalFee > 0 ? paymentChoice === "qr" || paymentChoice === "office" : paymentChoice === "exempt";
  const ready = Boolean(personReady && address.trim() && proofReady && paymentReady);
  const filteredAddresses = addressSuggestions.filter((item) => item.toLocaleLowerCase("cs-CZ").includes(address.toLocaleLowerCase("cs-CZ"))).slice(0, 4);
  const appointment = selectedDay && selectedTime ? `${selectedDay}. 7. 2026 · ${selectedTime}` : "Bez rezervace";

  if (submitted) return <main className="situation-page"><div className="situation-page__inner situation-success"><span><CheckCircle2 size={40} /></span><p>Online příprava je hotová</p><h1>Na úřad můžete přijít a změnu dokončit</h1>{appointment !== "Bez rezervace" ? <div className="situation-success__appointment"><CalendarDays size={23} /><span><small>Rezervovaný termín</small><strong>{appointment}</strong><b>L. Váchy 602, Zlín–Prštné</b></span></div> : <div className="situation-success__appointment"><MapPin size={23} /><span><small>Návštěva bez rezervace</small><strong>Přijďte během úředních hodin</strong><b>L. Váchy 602, Zlín–Prštné</b></span></div>}<ul><li><Check size={17} /> Nová adresa: {address}</li><li><Check size={17} /> Podklad k bydlení je předaný ke kontrole</li><li><Check size={17} /> {paymentChoice === "qr" ? "Zvolili jste úhradu pomocí QR kódu" : "Poplatek zaplatíte na místě"}</li></ul><p>Na přepážce prokážete svou totožnost a podepíšete přihlašovací lístek. Úředník už bude mít připravené údaje i elektronicky doložený dokument.</p><button type="button" onClick={() => navigate("/moje-podani")}>Zobrazit v Mých podáních</button><button className="situation-link-button" type="button" onClick={() => navigate("/")}>Zpět na nástěnku</button></div></main>;

  return <main className="situation-page"><div className="situation-page__inner">
    <BackButton className="situation-back" label="Zpět na životní situace" onClick={() => navigate("/zivotni-situace")} />
    <header className="situation-hero"><div><p>Bydlení a město</p><h1>Stěhuji se nebo měním trvalý pobyt</h1><span>Údaje, dokument a platbu si připravíte online. Na úřadě pak jen prokážete totožnost a změnu dokončíte.</span></div><aside><small>Správní poplatek</small><strong>50 Kč</strong><span>osoby mladší 15 let neplatí</span></aside></header>
    <div className="situation-facts"><span><CalendarDays size={19} /><b>Na úřadě asi 10 minut</b></span><span><MapPin size={19} /><b>L. Váchy 602</b></span><span><ShieldCheck size={19} /><b>Online příprava + osobní dokončení</b></span></div>
    <section className="situation-explainer"><Info size={21} /><div><strong>Co vyřídíte online a co na úřadě?</strong><p>Online zadáte novou adresu, doložíte vztah k bydlení a zvolíte platbu. Osobně už jen prokážete totožnost a podepíšete zákonem stanovený přihlašovací lístek.</p></div></section>
    <div className="situation-layout"><form className="situation-form" onSubmit={(event) => { event.preventDefault(); if (ready) setSubmitted(true); }}><p className="form-required-note"><span>*</span> Povinné: alespoň jedna osoba, nová adresa, vztah k bydlení a způsob úhrady.</p>
      <section className="situation-step"><header><b>1</b><div><p>Osoba a nové bydliště</p><h2>Za koho změnu připravujete?</h2></div></header>
        <div className="moving-people"><button className={includeSelf ? "moving-person is-selected" : "moving-person"} type="button" onClick={() => setIncludeSelf((value) => !value)}><span className="moving-person__check">{includeSelf && <Check size={16} />}</span><span><strong>Jan Novák</strong><small>Vy · správní poplatek 50 Kč</small></span><b>{includeSelf ? "Zahrnuto" : "Přidat"}</b></button>{entrustedPeople.map((birthNumber, index) => <div className={savedPeople[index] ? "moving-entrusted is-saved" : "moving-entrusted"} key={index}><div><label className="situation-field"><span>Rodné číslo svěřené osoby {index + 1}</span><div><input disabled={savedPeople[index]} value={birthNumber} onChange={(event) => { setEntrustedPeople((people) => people.map((item, itemIndex) => itemIndex === index ? event.target.value : item)); setSavedPeople((items) => items.map((item, itemIndex) => itemIndex === index ? false : item)); }} placeholder="Například 150315/1234" /></div></label>{savedPeople[index] && <div className="moving-person-fee"><span><CheckCircle2 size={16} /> Osoba je uložená</span><div><button className={!exemptPeople[index] ? "is-active" : ""} type="button" onClick={() => setExemptPeople((items) => items.map((item, itemIndex) => itemIndex === index ? false : item))}>Poplatek 50 Kč</button><button className={exemptPeople[index] ? "is-active" : ""} type="button" onClick={() => setExemptPeople((items) => items.map((item, itemIndex) => itemIndex === index ? true : item))}>Osvobozeno · osoba mladší 15 let</button></div></div>} {!savedPeople[index] && <button className="moving-save-person" type="button" disabled={birthNumber.replace(/\D/g, "").length < 9} onClick={() => { setSavedPeople((items) => items.map((item, itemIndex) => itemIndex === index ? true : item)); setExemptPeople((items) => items.map((item, itemIndex) => itemIndex === index ? isUnder15(birthNumber) : item)); }}>Potvrdit a přidat osobu</button>}</div><button type="button" onClick={() => { setEntrustedPeople((people) => people.filter((_, itemIndex) => itemIndex !== index)); setSavedPeople((items) => items.filter((_, itemIndex) => itemIndex !== index)); setExemptPeople((items) => items.filter((_, itemIndex) => itemIndex !== index)); }} aria-label="Odebrat osobu"><X size={18} /></button></div>)}</div>
        <button className="moving-add-person" type="button" onClick={() => { setEntrustedPeople((people) => [...people, ""]); setSavedPeople((items) => [...items, false]); setExemptPeople((items) => [...items, false]); }}>+ Přidat svěřenou osobu</button>
        <h3 className="situation-subheading">Kam se osoba stěhuje?</h3><div className="situation-address-wrap"><label className="situation-field"><span>Nová adresa ve Zlíně</span><div><MapPin size={18} /><input value={address} onFocus={() => setShowSuggestions(true)} onChange={(event) => { setAddress(event.target.value); setShowSuggestions(true); }} placeholder="Začněte psát ulici a číslo domu" /></div></label>{showSuggestions && address.length > 1 && filteredAddresses.length > 0 && <div className="situation-address-suggestions">{filteredAddresses.map((item) => <button type="button" onClick={() => { setAddress(item); setShowSuggestions(false); }} key={item}><MapPin size={16} /><span>{item}</span></button>)}</div>}</div>{address && <div className="situation-address-note"><CheckCircle2 size={18} /><span><strong>Použijeme zadanou adresu</strong><small>Nemusíte ji vybírat z nabídky. To se hodí například u nové stavby nebo dosud nezařazené adresy.</small></span></div>}
      </section>
      <section className="situation-step"><header><b>2</b><div><p>Vztah k bydlení</p><h2>Jaké máte oprávnění byt užívat?</h2></div></header><div className="situation-choice-grid">{[["owner","Jsem vlastník"],["tenant","Mám nájemní smlouvu"],["subtenant","Mám podnájemní smlouvu"],["consent","Mám souhlas vlastníka"]].map(([value,label]) => <button className={proofType === value ? "is-active" : ""} type="button" onClick={() => { setProofType(value); setFileName(""); }} key={value}><Building2 size={19} /><span>{label}</span>{proofType === value && <Check size={16} />}</button>)}</div>{proofType === "owner" ? <div className="situation-verified"><ShieldCheck size={18} /><span><strong>Vlastnictví ověříme v katastru</strong><small>Pokud údaj nenajdeme automaticky, ozveme se vám ještě před návštěvou.</small></span></div> : <><input ref={fileInput} hidden type="file" accept="application/pdf,image/*" onChange={(event) => setFileName(event.target.files?.[0]?.name ?? "")} />{fileName ? <div className="situation-file"><FileText size={20} /><span><strong>{fileName}</strong><small>Dokument je přiložený a připravený ke kontrole</small></span><button type="button" onClick={() => setFileName("")} aria-label="Odebrat dokument"><X size={17} /></button></div> : <button className="situation-upload" type="button" onClick={() => fileInput.current?.click()}><Upload size={21} /><span><strong>Přiložit dokument</strong><small>PDF, JPG nebo PNG</small></span></button>}</>}</section>
      <section className="situation-step"><header><b>3</b><div><p>Návštěva úřadu</p><h2>Chcete si rezervovat termín?</h2></div></header><div className="situation-office"><MapPin size={20} /><div><strong>Evidence obyvatel</strong><span>L. Váchy 602, Zlín–Prštné</span><small>Rezervace není nutná. Po odeslání přípravy můžete přijít kdykoliv během úředních hodin.</small></div></div><div className="appointment-calendar"><header><button type="button" aria-label="Předchozí měsíc"><ChevronLeft size={18} /></button><strong>Červenec 2026</strong><button type="button" aria-label="Následující měsíc"><ChevronRight size={18} /></button></header><div className="appointment-calendar__week"><span>Po</span><span>Út</span><span>St</span><span>Čt</span><span>Pá</span><span>So</span><span>Ne</span></div><div className="appointment-calendar__days"><i /><i />{calendarDays.map((day) => <button className={selectedDay === day ? "is-selected" : availableDays.includes(day) ? "is-available" : ""} type="button" disabled={!availableDays.includes(day)} onClick={() => { setSelectedDay(day); setSelectedTime(""); }} key={day}>{day}{availableDays.includes(day) && <small />}</button>)}</div></div>{selectedDay && <div className="appointment-times"><span>Dostupné časy pro {selectedDay}. 7.</span><div>{timeSlots.map((time) => <button className={selectedTime === time ? "is-active" : ""} type="button" onClick={() => setSelectedTime(time)} key={time}>{time}</button>)}</div></div>}<button className="appointment-without" type="button" onClick={() => { setSelectedDay(null); setSelectedTime(""); }}><CalendarDays size={17} /> Přijdu bez rezervace</button></section>
      <section className="situation-more"><h2>Co je dobré vědět</h2><details><summary>Co se stane při návštěvě úřadu? <ChevronDown size={17} /></summary><p>Úředník ověří vaši totožnost a připravené údaje. Podepíšete přihlašovací lístek a dostanete potvrzení o změně. Samotná návštěva obvykle zabere přibližně 10 minut.</p></details><details><summary>Co následuje po změně adresy? <ChevronDown size={17} /></summary><p>Změna se zapíše do evidence obyvatel nejpozději do tří pracovních dnů. Poté požádáte o nový občanský průkaz. Řidičský průkaz se při změně trvalého pobytu nemění.</p></details><details><summary>Koho dalšího je potřeba informovat? <ChevronDown size={17} /></summary><p>Portál vám po dokončení nabídne kontrolu poplatku za odpad, aktualizaci údajů o psovi a případné parkovací oprávnění. Soukromým institucím, například bance nebo pojišťovně, oznamujete změnu samostatně.</p></details><details><summary>Úřední hodiny a kontakt <ChevronDown size={17} /></summary><p>Evidence obyvatel na L. Váchy 602 je otevřena v pondělí a středu 8:00–17:00 a v úterý a pátek 8:00–13:00.</p></details></section>
      <button className="situation-submit" type="submit" disabled={!ready}>Dokončit online přípravu <CheckCircle2 size={18} /></button>
    </form>
    <aside className="situation-payment"><header><span><CreditCard size={23} /></span><div><p>Správní poplatek</p><h2>{totalFee.toLocaleString("cs-CZ")} Kč</h2></div></header><p>{includeSelf ? "Jan Novák: 50 Kč" : "Jan Novák není zahrnut"}{savedPeople.map((saved, index) => saved ? ` · Osoba ${index + 1}: ${exemptPeople[index] ? "osvobozena" : "50 Kč"}` : "").join("")}</p>
      <div className="payment-choice">{totalFee > 0 ? <><button className={paymentChoice === "qr" ? "is-active" : ""} type="button" onClick={() => setPaymentChoice("qr")}><QrCode size={20} /><span><strong>Zaplatím QR kódem</strong><small>Bankovním převodem před návštěvou</small></span>{paymentChoice === "qr" && <Check size={17} />}</button><button className={paymentChoice === "office" ? "is-active" : ""} type="button" onClick={() => setPaymentChoice("office")}><CreditCard size={20} /><span><strong>Zaplatím na místě</strong><small>Při návštěvě přepážky</small></span>{paymentChoice === "office" && <Check size={17} />}</button></> : <button className={paymentChoice === "exempt" ? "is-active" : ""} type="button" onClick={() => setPaymentChoice("exempt")}><ShieldCheck size={20} /><span><strong>Potvrdit osvobození</strong><small>Všechny zahrnuté osoby jsou mladší 15 let</small></span>{paymentChoice === "exempt" && <Check size={17} />}</button>}</div>
      {paymentChoice === "qr" && <div className="situation-qr"><QrCode size={126} strokeWidth={1.4} /><span>Naskenujte v bankovní aplikaci</span><dl><div><dt>Částka</dt><dd>{totalFee.toLocaleString("cs-CZ")} Kč</dd></div><div><dt>Účet města</dt><dd>000000-123456789 / 0800</dd></div><div><dt>Variabilní symbol</dt><dd>0201154470</dd></div><div><dt>Konstantní symbol</dt><dd>0379</dd></div><div><dt>Zpráva</dt><dd>Změna trvalého pobytu</dd></div></dl></div>}{paymentChoice === "office" && <div className="situation-payment__paid"><CheckCircle2 size={20} /><span><strong>Zaplatíte při návštěvě</strong><small>Úředník vás provede úhradou poplatku.</small></span></div>}{paymentChoice === "exempt" && <div className="situation-payment__paid"><ShieldCheck size={20} /><span><strong>Poplatek se neplatí</strong><small>Od poplatku jsou osvobozeni občané mladší 15 let.</small></span></div>}
    </aside>
    </div>
  </div></main>;
}
